// Generated by CoffeeScript 1.6.3
(function() {
  var assert;

  assert = require('assert');

  suite('Integration:Connection', function() {
    return test('Creating a user should sign that user in and connect to the network.', function(done, server, client) {
      server["eval"](function() {
        return Meteor.users.find().observeChanges({
          added: function(doc) {
            return emit('done');
          }
        });
      });
      client["eval"](function() {
        return Accounts.createUser({
          username: 'matty',
          email: 'matty@gmail.com',
          password: 'password',
          profile: {
            connection: false,
            account: 'free'
          }
        });
      });
      return server.once('done', function() {
        return done();
      });
    });
  });

}).call(this);
