// Generated by CoffeeScript 1.6.3
(function() {
  var assert;

  assert = require('assert');

  suite('Channels', function() {
    test('uniqueness', function(done, server, client) {
      client["eval"](function() {
        return Accounts.createUser({
          username: 'matt',
          password: 'password',
          profile: {
            connecting: true
          }
        }, function() {
          Channels.insert({
            owner: Meteor.userId(),
            name: '#channel'
          });
          Channels.insert({
            owner: Meteor.userId(),
            name: '#channel'
          });
          return Channels.find().observe({
            removed: function() {
              return emit('removed');
            }
          });
        });
      });
      return client.once('removed', function() {
        return done();
      });
    });
    return test('no whitespace', function(done, server, client) {
      client["eval"](function() {
        return Accounts.createUser({
          username: 'matt',
          password: 'password',
          profile: {
            connecting: true
          }
        }, function() {
          Channels.insert({
            owner: Meteor.userId(),
            name: '#channel name'
          });
          return Channels.find().observe({
            removed: function() {
              return emit('removed');
            }
          });
        });
      });
      return client.once('removed', function() {
        return done();
      });
    });
  });

}).call(this);
